version: "3.9"
services:
  bot:
   restart: unless-stopped
   profiles:
      - "dev"
   build:
      dockerfile: Dockerfile
   working_dir: /internal/tmpweather
   env_file:
      - .env
      - .dbconf.env
   ports:
      - "127.0.0.1:8080:8080"
   links:
      - postgres
   depends_on:
      - postgres

  postgres:
    image: "postgres:15-alpine"
    restart: unless-stopped
    profiles:
      - "test"
      - "dev"
    ports:
      - "5432:5432"
    environment:
      PGDATA: "/data/postgres"
    env_file:
      - .dbconf.env
    volumes:
      - postgres:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrate:
    profiles:
      - "dev"
    image: migrate/migrate
    env_file:
      - .dbconf.env
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable", "up"]
    links:
      - postgres
    depends_on:
      - postgres

volumes:
    postgres: